// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rent_a_car_mvc.Data;

#nullable disable

namespace rent_a_car_mvc.Migrations
{
    [DbContext(typeof(RentACarContext))]
    [Migration("20231220082416_AddCustomers")]
    partial class AddCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rent_a_car_mvc.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationPlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Aston Martin",
                            Model = "Vanquish",
                            RegistrationPlate = "AM0-V-001"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Mercedes Benz",
                            Model = "S Class",
                            RegistrationPlate = "MB0-S-001"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Rolls Royce",
                            Model = "Wraith",
                            RegistrationPlate = "RR0-W-001"
                        });
                });

            modelBuilder.Entity("rent_a_car_mvc.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2002, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "seferibrahim2@gmail.com",
                            Name = "Ibrahim Sefer",
                            Telephone = "+905363344840"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2001, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnsmith@gmail.com",
                            Name = "John Smith",
                            Telephone = "+905361123440"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2000, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "markmarkovich@gmail.com",
                            Name = "Mark Markovich",
                            Telephone = "+905369977660"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
